name: Backend Build and Test

on:
  push:
    paths:
      - 'mess-backend/**'
  pull_request:
    paths:
      - 'mess-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # or your backend node version

      - name: Install dependencies
        run: |
          cd mess-backend
          npm install

      - name: Run backend tests
        run: |
          cd mess-backend
          npm test   # or your backend test command
