name: Frontend CI

on:
  push:
    paths:
      - 'mess-frontend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd mess-frontend
          npm install

      - name: Build app
        run: |
          cd mess-frontend
          npm run build
