- name: Set up Kubernetes Master Node
  hosts: master
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add Kubernetes repo
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Install kubelet, kubeadm, kubectl
      yum:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes

    - name: Disable SELinux
      command: setenforce 0
      ignore_errors: true

    - name: Initialize Kubernetes Cluster
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: init_output
      ignore_errors: true

    - name: Create kube config for ec2-user
      shell: |
        mkdir -p /home/ec2-user/.kube
        cp -i /etc/kubernetes/admin.conf /home/ec2-user/.kube/config
        chown ec2-user:ec2-user /home/ec2-user/.kube/config
      when: init_output.rc == 0

    - name: Install Calico Network Plugin
      become_user: ec2-user
      shell: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml